# Setup
title:               Hic sunt leones
tagline:             AKA Giovanni Santini's personal blog. For real, yeah.
description:
  A blog made from an IT lover about IT and other stuff (insert madness here).
  Based on the awesome <a href="https://github.com/poole/lanyon" target="_blank">Lanyon</a> theme,
  made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.
url:                 https://itachisan.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

exclude:
  - templates
  - LICENSE.md
  - README.md
  - LICENSE.lanyon
  - README.lanyon

# Gems
plugins:
  - jekyll-paginate
  - jekyll-minifier

# About/contact
author:
  name:              Giovanni Santini
  url:               https://www.linkedin.com/in/giovanni-santini
  email:             giovannisantini93@yahoo.it

# This website's repo
github:
  repo:           https://github.com/ItachiSan/itachisan.github.io

# Custom vars
version:             1.0.3
google_analytics:    UA-61816764-1

# Allow AddToAny integration.
addtoany: true

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: giovannisantini

# Theme customization
theme:
  # You can customize the color via the correct code, listed below:
  # - Red:     08
  # - Orange:  09
  # - Yellow:  0a
  # - Green:   0b
  # - Cyan:    0c
  # - Blue:    0d
  # - Magenta: 0e
  # - Brown:   0f
  # Any invalid input will be silently ignored.
  color:   08
  # Make the sidebar to overlay the content, rather than pushing it.
  overlay: true
  # Reverse the position of the sidebar (from left to right side)
  reverse: false
